# Generated by Django 2.1.5 on 2019-01-29 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_auto_20190128_1909'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='descriprion',
            new_name='description',
        ),
    ]
