# Generated by Django 2.1.5 on 2019-01-29 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_auto_20190129_1648'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='description_charfields',
            field=models.CharField(blank=True, max_length=200, verbose_name='Descrição em Charfield'),
        ),
    ]
