# Generated by Django 2.1.5 on 2019-01-29 17:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_course_description_charfields'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='description_charfields',
        ),
    ]
