# Generated by Django 2.1.5 on 2019-02-15 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0010_auto_20190215_1200'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='Announcement',
            new_name='announcement',
        ),
    ]
