# Generated by Django 2.1.5 on 2019-03-04 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0002_reply_thread'),
    ]

    operations = [
        migrations.AddField(
            model_name='thread',
            name='slug',
            field=models.SlugField(default='default-slug', max_length=100, unique=True, verbose_name='Identificador'),
            preserve_default=False,
        ),
    ]
